### PR TITLE
add support for HID touch screen

### PR DESCRIPTION
**Pull request by ayavilevich**
A different implementation of an "absolute mouse" that works with Android devices.
In response to https://github.com/arpruss/USBComposite_stm32f1/issues/63

@arpruss , you are welcome to merge this as a whole or just parts to the main library if you want.

### CODE REVIEW

**Comment by arpruss** [comment]
Would it work any worse if we made the range 0-16383 or 0-4095? That would make it easier to convert data from other sources.

**Comment by ayavilevich** [comment]
@arpruss I don't know. I believe this descriptor was based on a descriptor of some actual hardware. If you want to send me some alternate bytes I can try them out and see if it still works. I don't have the experience to modify the descriptor myself.

What other sources are you talking about? As far as I see, the range needs to be mapped to the screen resolution of the main display of the host device. Mapping will vary with each different host device.

**Comment by arpruss** [comment]
By sources I mean things like a potentiometer or touch screen device that generate the digitizer data.

I changed the range to 16383, and added an example.

I am not sure dragging works on Windows but it does work on Android.

**Comment by ayavilevich** [comment]
Ok, got it about external devices like a potentiometer.

Thanks for merging and completing the changes. Glad to contribute to this lib which is useful to me.
Some of the changes you made broke the functionality. I have added a comment in the relevant commit.

**Comment by arpruss** [comment]
Sorry about that. I changed the range to 4K, which fits the ADC range of the device well.

**Pull request merged**
